# <b>AI Project</b>
## <b>Flight Fare Prediction System</b>
## Name: Khadija Ashfaq
## RollNumber: SU92-BSAIM-S25-036

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder

<div class="alert alert-block alert-success">
    <h1>1. Data Reading</h1>
</div>

#### Dataset: <a>https://www.kaggle.com/datasets/harshavarshney/flight-fare/data</a>

In [2]:
data = pd.read_csv('flight_fare.csv')

<div class="alert alert-block alert-success">
    <h1>2. Data Exploration</h1>
</div>

In [3]:
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR ? DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU ? IXR ? BBI ? BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL ? LKO ? BOM ? COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU ? NAG ? BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR ? NAG ? DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
data.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU ? BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU ? BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR ? DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR ? DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [5]:
print('rows:', data.shape[0])
print('columns', data.shape[1])

rows: 10683
columns 11

In [6]:
print(data.columns)

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [7]:
data.count()

Airline            10683
Date_of_Journey    10683
Source             10683
Destination        10683
Route              10682
Dep_Time           10683
Arrival_Time       10683
Duration           10683
Total_Stops        10682
Additional_Info    10683
Price              10683
dtype: int64

In [8]:
data.nunique

<bound method DataFrame.nunique of            Airline Date_of_Journey    Source Destination  \
0           IndiGo      24/03/2019  Banglore   New Delhi
1        Air India       1/05/2019   Kolkata    Banglore
2      Jet Airways       9/06/2019     Delhi      Cochin
3           IndiGo      12/05/2019   Kolkata    Banglore
4           IndiGo      01/03/2019  Banglore   New Delhi
...            ...             ...       ...         ...
10678     Air Asia       9/04/2019   Kolkata    Banglore
10679    Air India      27/04/2019   Kolkata    Banglore
10680  Jet Airways      27/04/2019  Banglore       Delhi
10681      Vistara      01/03/2019  Banglore   New Delhi
10682    Air India       9/05/2019     Delhi      Cochin

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
0                  BLR ? DEL    22:20  01:10 22 Mar   2h 50m    non-stop
1      CCU ? IXR ? BBI ? BLR    05:50         13:15   7h 25m     2 stops
2      DEL ? LKO ? BOM ? COK    09:25  04:25 10 Jun      19h     2 stops
3            CCU ? NAG ? BLR    18:05         23:30   5h 25m      1 stop
4            BLR ? NAG ? DEL    16:50         21:35   4h 45m      1 stop
...                      ...      ...           ...      ...         ...
10678              CCU ? BLR    19:55         22:25   2h 30m    non-stop
10679              CCU ? BLR    20:45         23:20   2h 35m    non-stop
10680              BLR ? DEL    08:20         11:20       3h    non-stop
10681              BLR ? DEL    11:30         14:10   2h 40m    non-stop
10682  DEL ? GOI ? BOM ? COK    10:55         19:15   8h 20m     2 stops

      Additional_Info  Price
0             No info   3897
1             No info   7662
2             No info  13882
3             No info   6218
4             No info  13302
...               ...    ...
10678         No info   4107
10679         No info   4145
10680         No info   7229
10681         No info  12648
10682         No info  11753

[10683 rows x 11 columns]>

In [9]:
data.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [11]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

<div class="alert alert-block alert-success">
    <h1>3. Data Pre-Processing</h1>
</div>

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [13]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [14]:
data['Airline'].isnull().sum()

np.int64(0)

In [15]:
data.shape

(10683, 11)

In [16]:
data['Date_of_Journey'] = pd.to_datetime(data['Date_of_Journey'])

data['Journey_Day'] = data['Date_of_Journey'].dt.day
data['Journey_Month'] = data['Date_of_Journey'].dt.month

data.drop(['Date_of_Journey'], axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19236\1134730885.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Date_of_Journey'] = pd.to_datetime(data['Date_of_Journey'])

In [17]:
def convert_duration(x):
    h, m = 0, 0
    
    if 'h' in x:
        h = int(x.split('h')[0])
    if 'm' in x:
        m = int(x.split('m')[0].split()[-1])
        
    return h*60 + m

data['Duration'] = data['Duration'].apply(convert_duration)

In [18]:
data['Dep_Hour'] = pd.to_datetime(data['Dep_Time']).dt.hour
data['Dep_Min'] = pd.to_datetime(data['Dep_Time']).dt.minute

data['Arrival_Hour'] = pd.to_datetime(data['Arrival_Time']).dt.hour
data['Arrival_Min'] = pd.to_datetime(data['Arrival_Time']).dt.minute

data.drop(['Dep_Time', 'Arrival_Time'], axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19236\2259885893.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Dep_Hour'] = pd.to_datetime(data['Dep_Time']).dt.hour
C:\Users\HP\AppData\Local\Temp\ipykernel_19236\2259885893.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Dep_Min'] = pd.to_datetime(data['Dep_Time']).dt.minute
C:\Users\HP\AppData\Local\Temp\ipykernel_19236\2259885893.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Arrival_Hour'] = pd.to_datetime(data['Arrival_Time']).dt.hour
C:\Users\HP\AppData\Local\Temp\ipykernel_19236\2259885893.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Arrival_Min'] = pd.to_datetime(data['Arrival_Time']).dt.minute

In [19]:
data.drop(['Route'], axis=1, inplace=True)

In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import joblib

# Dictionary to store all encoders
encoders = {}

# Columns to encode (categorical only)
categorical_cols = [
    'Airline',
    'Source',
    'Destination',
    'Total_Stops',
    'Additional_Info'
]

# Apply Label Encoding and store encoders
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    encoders[col] = le

# Save encoders to file
joblib.dump(encoders, 'encoders.pkl')

print("Encoders saved successfully!")

Encoders saved successfully!

In [21]:
data.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min
0,3,0,5,170,4,8,3897,24,3,22,20,1,10
1,1,3,0,445,1,8,7662,1,5,5,50,13,15
2,4,2,1,1140,1,8,13882,9,6,9,25,4,25
3,3,3,0,325,0,8,6218,12,5,18,5,23,30
4,3,0,5,285,0,8,13302,1,3,16,50,21,35

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  int64
 1   Source           10683 non-null  int64
 2   Destination      10683 non-null  int64
 3   Duration         10683 non-null  int64
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  int64
 6   Price            10683 non-null  int64
 7   Journey_Day      10683 non-null  int32
 8   Journey_Month    10683 non-null  int32
 9   Dep_Hour         10683 non-null  int32
 10  Dep_Min          10683 non-null  int32
 11  Arrival_Hour     10683 non-null  int32
 12  Arrival_Min      10683 non-null  int32
dtypes: int32(6), int64(7)
memory usage: 834.7 KB

In [23]:
data['Price'] = data['Price'].fillna(data['Price'].mean())

In [24]:
def fillnaMean(cols):
    for i in cols:
        data[i] = data[i].fillna(data[i].mean())

columns = ['Price']

fillnaMean(columns)

In [25]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  int64
 1   Source           10683 non-null  int64
 2   Destination      10683 non-null  int64
 3   Duration         10683 non-null  int64
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  int64
 6   Price            10683 non-null  int64
 7   Journey_Day      10683 non-null  int32
 8   Journey_Month    10683 non-null  int32
 9   Dep_Hour         10683 non-null  int32
 10  Dep_Min          10683 non-null  int32
 11  Arrival_Hour     10683 non-null  int32
 12  Arrival_Min      10683 non-null  int32
dtypes: int32(6), int64(7)
memory usage: 834.7 KB

In [26]:
data['Price'] = data['Price'].replace(',', '', regex=True).astype(float)

In [27]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  int64
 1   Source           10683 non-null  int64
 2   Destination      10683 non-null  int64
 3   Duration         10683 non-null  int64
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  int64
 6   Price            10683 non-null  float64
 7   Journey_Day      10683 non-null  int32
 8   Journey_Month    10683 non-null  int32
 9   Dep_Hour         10683 non-null  int32
 10  Dep_Min          10683 non-null  int32
 11  Arrival_Hour     10683 non-null  int32
 12  Arrival_Min      10683 non-null  int32
dtypes: float64(1), int32(6), int64(6)
memory usage: 834.7 KB

In [28]:
data.to_csv('cleaned_data.csv', index=False)
print("Cleaned data saved!")

Cleaned data saved!

<div class="alert alert-block alert-success">
    <h1>4. Train-Test Splitting</h1>
</div>

In [29]:
data = pd.read_csv('cleaned_data.csv')

In [30]:
data.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Journey_Day,Journey_Month,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min
0,3,0,5,170,4,8,3897.0,24,3,22,20,1,10
1,1,3,0,445,1,8,7662.0,1,5,5,50,13,15
2,4,2,1,1140,1,8,13882.0,9,6,9,25,4,25
3,3,3,0,325,0,8,6218.0,12,5,18,5,23,30
4,3,0,5,285,0,8,13302.0,1,3,16,50,21,35

In [31]:
data.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Journey_Day', 'Journey_Month', 'Dep_Hour',
       'Dep_Min', 'Arrival_Hour', 'Arrival_Min'],
      dtype='str')

In [32]:

X = data.drop('Price', axis=1)
y = data['Price']

In [33]:
print(y.shape)

(10683,)

In [34]:
if np.isnan(y).any():
    # Fill remaining NaNs with the mean
    y = np.nan_to_num(y, nan=np.nanmean(y))

In [35]:
X.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Journey_Day,Journey_Month,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min
0,3,0,5,170,4,8,24,3,22,20,1,10
1,1,3,0,445,1,8,1,5,5,50,13,15
2,4,2,1,1140,1,8,9,6,9,25,4,25
3,3,3,0,325,0,8,12,5,18,5,23,30
4,3,0,5,285,0,8,1,3,16,50,21,35

In [36]:
y.head()

0     3897.0
1     7662.0
2    13882.0
3     6218.0
4    13302.0
Name: Price, dtype: float64

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
print(X.dtypes)

Airline            int64
Source             int64
Destination        int64
Duration           int64
Total_Stops        int64
Additional_Info    int64
Journey_Day        int64
Journey_Month      int64
Dep_Hour           int64
Dep_Min            int64
Arrival_Hour       int64
Arrival_Min        int64
dtype: object

In [39]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(8546, 12) (8546,)
(2137, 12) (2137,)

<div class="alert alert-block alert-success">
    <h1>5. Model Application</h1>
</div>

## Training Model using Regression

In [40]:
print("-- Training the Model using Random Forest Regressor --")
# Initialize the Regressor
model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

-- Training the Model using Random Forest Regressor --

RandomForestRegressor(random_state=42)

In [41]:
import pickle

# Saving the Trained Regression Model
pickle.dump(model_rf, open('model.pkl', 'wb'))

print("model.pkl saved successfully!")

model.pkl saved successfully!

In [42]:
joblib.dump(model_rf, "model.pkl", compress=('xz', 9))

['model.pkl']

In [43]:
import joblib
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [44]:
import joblib

# Load Saved Model
model_rf = joblib.load(open('model.pkl', 'rb'))

# Test it with one row from test set
prediction = model_rf.predict(X_test.head(1))

print(f"Test Prediction: {prediction}")

Test Prediction: [11073.07]

<div class="alert alert-block alert-success">
    <h1>6. Model Accuracy</h1>
</div>

In [45]:
y_pred = model_rf.predict(X_test)

accuracy = r2_score(y_test, y_pred)
error = mean_absolute_error(y_test, y_pred)

print("R2 Score:", accuracy)
print("Mean Absolute Error:", error)

R2 Score: 0.8614590691078134
Mean Absolute Error: 670.795195055036

<div class="alert alert-block alert-success">
    <h1>7. Application Phase</h1>
</div>

In [46]:
import pandas as pd
import numpy as np
import pickle
import joblib

# Load Saved Model & Encoders
model = joblib.load(open('model.pkl', 'rb'))
encoders = joblib.load('encoders.pkl')

# Function for Encoding
def encode_cols(le, value):
    if value in le.classes_:
        return le.transform([value])[0]
    else:
        return -1

print("----- Flight Fare Prediction -----")

# User Inputs
user_input = {
    
    "Airline": input("Airline: "),
    "Source": input("Source: "),
    "Destination": input("Destination: "),
    
    "Duration": int(input("Duration (in minutes): ")),
    
    "Total_Stops": input("Total Stops: "),
    
    "Additional_Info": input("Additional Info: "),
    
    "Journey_Day": int(input("Journey Day: ")),
    "Journey_Month": int(input("Journey Month: ")),
    
    "Dep_Hour": int(input("Departure Hour (0-23): ")),
    "Dep_Min": int(input("Departure Minute (0-59): ")),
    
    "Arrival_Hour": int(input("Arrival Hour (0-23): ")),
    "Arrival_Min": int(input("Arrival Minute (0-59): "))
}

# Encoding Categorical Columns
categorical_cols = [
    'Airline',
    'Source',
    'Destination',
    'Total_Stops',
    'Additional_Info'
]

for col in categorical_cols:
    user_input[col] = encode_cols(encoders[col], user_input[col])

# Features Order (same as training)
features = [
    'Airline',
    'Source',
    'Destination',
    'Duration',
    'Total_Stops',
    'Additional_Info',
    'Journey_Day',
    'Journey_Month',
    'Dep_Hour',
    'Dep_Min',
    'Arrival_Hour',
    'Arrival_Min'
]

# Convert Input into Array
X = np.array([[user_input[col] for col in features]])

# Predict Flight Fare
prediction = model.predict(X)

print("\nPredicted Flight Fare:", prediction[0])

----- Flight Fare Prediction -----

Predicted Flight Fare: 7208.78

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(